-- Таблица для учета всех NFT минтов
CREATE TABLE IF NOT EXISTS public.nft_mints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_address TEXT NOT NULL,
    nft_mint_address TEXT UNIQUE, -- ✅ Адрес NFT mint
    nft_type TEXT,
    nft_rarity TEXT,
    nft_data JSONB,
    mint_price DECIMAL,
    mint_phase INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Индексы
CREATE INDEX IF NOT EXISTS idx_nft_mints_wallet ON public.nft_mints (wallet_address);
CREATE INDEX IF NOT EXISTS idx_nft_mints_created ON public.nft_mints (created_at DESC);

-- RLS
ALTER TABLE public.nft_mints ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read nft_mints" ON public.nft_mints 
FOR SELECT USING (true);

CREATE POLICY "Public insert nft_mints" ON public.nft_mints 
FOR INSERT WITH CHECK (true);



